require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Severity: error

  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Lint/EmptyClass:
  Enabled: false

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"
    - "db/migrate/*.rb"
    - "config/environments/*.rb"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "db/migrate/**/*.rb"

Rails/FilePath:
  EnforcedStyle: arguments

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    [
      "to",
      "to_not",
      "require",
      "require_relative",
      "describe",
      "it",
      "context",
      "exit",
      "validate_presence_of",
      "belong_to",
      "have_many",
      "raise",
      "puts",
      "desc",
      "redirect_to",
      "render",
    ]
  Enabled: true
  Exclude:
    - "db/migrate/*.rb"
    - "Gemfile"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/ContextWording:
  Enabled: true
  Exclude:
    - "spec/support/shared_contexts/*.rb"

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - "spec/mailers/**/*"
    - "spec/views/**/*"

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: false
