#!/bin/bash

set -eox pipefail

eval $(ci env)

export CI_BUILD_ID="$HEROKU_TEST_RUN_ID"
export CI_NAME="heroku"
export GIT_BRANCH="$HEROKU_TEST_RUN_BRANCH"
export GIT_COMMIT_SHA="$HEROKU_TEST_RUN_COMMIT_VERSION"
export GIT_COMMITTED_AT="$(date +%s)"

# run linter
bundle exec rubocop

# run the ruby test suite
bundle exec rake spec

# send report to code climate
./cc-test-reporter after-build --exit-code $?
